### PR TITLE
HOTFIX-3 Fix deprecation warning

### PR DESCRIPTION
**Pull request by sergiopr89**
Reported in the issue #3

### CODE REVIEW

**Comment by rhencke** [comment]
Thanks for this, @sergiopr89 - applied your fix locally until accepted. :)

**Comment by amitkot** [comment]
Upgrading to Xonsh 0.8.3 I now also get the deprecation warning that this PR fixes.
@xsteadfastx are you still maintaining this repo?

**Comment by xsteadfastx** [comment]
On Mo, 26. Nov 03:51, Amit Kotlovski wrote:
> Upgrading to Xonsh 0.8.3 I now also get the deprecation warning that this PR
> fixes.
> @xsteadfastx are you still maintaining this repo?

i will take care of it. but im not using xonsh anymore and honestly i
think the real docker bash completions should be used. this was just a
little fix and it doesnt even have all the docker commands included. so
if someone has a fun with mainting it.... this would live on.

**Comment by xsteadfastx** [comment]
uploaded the new version to pypi.

**Pull request merged**
